services:
  app_central:
    build: .
    image: bot_central:latest
    container_name: bot_central
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}
      PORT: 8001
    depends_on:
      - postgres_central
    networks:
      - central_network

  postgres_central:
    image: postgres:15
    container_name: postgres_central
    environment:
      POSTGRES_DB: bot_central
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_central_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - central_network

volumes:
  postgres_central_data:

networks:
  central_network:
    driver: bridge